[project]
name = "legal-ai-rag"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.14",
    "langchain-unstructured>=0.2.0",
    "unstructured[pdf]>=0.16.17",
    "langchain-text-splitters>=0.3.6",
    "pydantic>=2.10.5",
    "pdfplumber>=0.11.0",
]
